### ISSUE TITLE
Codebase no longer compatible with "torch==1.3.1"

### ISSUE THREAD

**Issue by MarcCoru** [IssamLaradji/GaussianProcessesDraft#3]
I tested with the latest torch (1.3.1). However, I ran into the following error:

steps to reproduce:
```
conda create -n gp-drf python=2.7 pip
conda activate gp-drf
pip install torch==1.3.1
python DRF_example.py 
GP_DRF/models/DRF.py:110: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  y_logprob = nn.LogSoftmax()(F)
Traceback (most recent call last):
  File "DRF_example.py", line 27, in <module>
    drf.fit(X, y, verbose=1, lr=1e-1, epochs=800)   
  File "projects/GP_DRF/models/DRF.py", line 131, in fit
    print "\n%d - loss: %.3f" % (i, loss.data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

It works with torch==0.4, though.

**Comment by IssamLaradji** [comment]
ah yah, thanks for the heads up, I will fix this just after the CVPR deadline on Nov 15!
